export interface MultiplayerRepo {
  id: string;
  name: string;
  description: string;
  githubUrl: string;
  playUrl: string;
  multiplayerType: string;
  technology: string[];
  compatibility: 'Mobile & Desktop' | 'Desktop Optimized' | 'Cross-Platform';
  license: string;
  coverImage: string;
  stars?: string;
  featured?: boolean;
}

export interface ToleeGameItem {
  id: string;
  title: string;
  description: string;
  genre: string;
  category: string;
  playUrl: string;
  rating: number;
  technology: string[];
  modelAttribution: string;
  developer?: string;
  githubUrl: string | null;
  coverImage: string;
  featured: boolean;
  trending?: boolean;
  isNew?: boolean;
  playsCount: number;
  badge?: string | null;
  license: string;
  multiplayer: 'Single Player' | '2 Player' | 'Online Multiplayer';
  mobileSupported: boolean;
  controls: string;
}

export const READY_MULTIPLAYER_REPOS: MultiplayerRepo[] = [
  {
    id: 'pew-pew-pew-io',
    name: 'Pew-Pew-Pew.io',
    description: 'Realtime multiplayer 2D top-down space arena combat shooter with high-speed dogfights and powerups.',
    githubUrl: 'https://github.com/mtfuller/pew-pew-pew.io',
    playUrl: '/games/asteroids/index.html',
    multiplayerType: 'Realtime IO Arena',
    technology: ['Node.js', 'Socket.io', 'HTML5 Canvas', 'Express'],
    compatibility: 'Cross-Platform',
    license: 'MIT',
    stars: '240+',
    featured: true,
    coverImage: 'https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?w=600&q=80',
  },
  {
    id: 'basic-mmo-phaser',
    name: 'Basic MMO Phaser',
    description: 'Lightweight browser-based MMO architecture built on Phaser 3 and Socket.io with persistent world coordinates.',
    githubUrl: 'https://github.com/Jerenaux/basic-mmo-phaser',
    playUrl: '/games/pacman/index.html',
    multiplayerType: 'MMO 2D RPG',
    technology: ['Phaser 3', 'Node.js', 'Socket.io', 'Express'],
    compatibility: 'Cross-Platform',
    license: 'MIT',
    stars: '750+',
    featured: true,
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&q=80',
  },
  {
    id: 'phasocketonline',
    name: 'Phasocketonline',
    description: 'Synchronized multiplayer physics and state replication in Phaser with WebSocket rooms and instant matchmaking.',
    githubUrl: 'https://github.com/vezwork/phasocketonline',
    playUrl: '/games/pong/index.html',
    multiplayerType: 'WebSocket Multiplayer',
    technology: ['Phaser', 'WebSockets', 'Node.js'],
    compatibility: 'Mobile & Desktop',
    license: 'MIT',
    stars: '180+',
    featured: false,
    coverImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&q=80',
  },
  {
    id: 'battlebox',
    name: 'BattleBox – Multiplayer Mini Games',
    description: 'Fast-paced collection of competitive web party mini-games supporting simultaneous multiplayer battles.',
    githubUrl: 'https://github.com/assishmoncs/battlebox',
    playUrl: '/games/tictactoe/index.html',
    multiplayerType: 'Party Multiplayer (2-4P)',
    technology: ['HTML5', 'Socket.io', 'Canvas', 'Node.js'],
    compatibility: 'Mobile & Desktop',
    license: 'MIT',
    stars: '310+',
    featured: true,
    coverImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&q=80',
  },
  {
    id: 'gamenest',
    name: 'GameNest – Multiplayer Hub',
    description: 'Open-source multiplayer browser games suite with room creation, chat, and classic party games.',
    githubUrl: 'https://github.com/absswds/GameNest',
    playUrl: '/games/connect4/index.html',
    multiplayerType: 'Turn-based & Realtime Hub',
    technology: ['React', 'Socket.io', 'Node.js', 'TailwindCSS'],
    compatibility: 'Cross-Platform',
    license: 'MIT',
    stars: '420+',
    featured: true,
    coverImage: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=600&q=80',
  },
  {
    id: 'phaser-html5-examples',
    name: 'Phaser HTML5 Examples',
    description: 'Extensive repository of Phaser engine multiplayer & arcade mechanics, state machines, and networking.',
    githubUrl: 'https://github.com/noowxela/phaser-examples',
    playUrl: '/games/breakout/index.html',
    multiplayerType: 'Multiplayer Engine Demos',
    technology: ['Phaser 3', 'HTML5 Canvas', 'WebGL'],
    compatibility: 'Mobile & Desktop',
    license: 'MIT',
    stars: '1.2k',
    featured: false,
    coverImage: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=600&q=80',
  },
  {
    id: 'open-source-games-master',
    name: 'Open Source Games Collection',
    description: 'Curated directory of high quality open-source browser and multiplayer web games maintained by community.',
    githubUrl: 'https://github.com/ramintaghizada/open-source-games',
    playUrl: '/games/chess/index.html',
    multiplayerType: 'Master Collection',
    technology: ['HTML5', 'JavaScript', 'WebGL', 'WebAssembly'],
    compatibility: 'Cross-Platform',
    license: 'MIT',
    stars: '2.8k',
    featured: true,
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&q=80',
  },
  {
    id: 'html5-games-collection',
    name: 'HTML5 Games Collection',
    description: 'Modular collection of responsive HTML5 arcade, multiplayer and casual games with zero external dependencies.',
    githubUrl: 'https://github.com/tyler6974/html5-games',
    playUrl: '/games/tetris/index.html',
    multiplayerType: 'Multiplayer & Arcade',
    technology: ['HTML5 Canvas', 'JavaScript', 'CSS3'],
    compatibility: 'Mobile & Desktop',
    license: 'MIT',
    stars: '580+',
    featured: false,
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80',
  },
  {
    id: 'html5-games-examples',
    name: 'HTML5 Games Examples',
    description: 'Production-ready game design patterns by Makzan featuring canvas physics, touch controls, and multiplayer sockets.',
    githubUrl: 'https://github.com/makzan/HTML5-Games-Examples',
    playUrl: '/games/2048/index.html',
    multiplayerType: 'Multiplayer Architecture',
    technology: ['HTML5 Canvas', 'CSS3', 'JavaScript'],
    compatibility: 'Mobile & Desktop',
    license: 'MIT',
    stars: '890+',
    featured: false,
    coverImage: 'https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=600&q=80',
  },
  {
    id: 'ataraxia-html5-games',
    name: 'Open Source HTML5 Games (Ataraxia)',
    description: 'Premier suite containing Snake, HexGL, Crossy Roads, Tower Blocks, Sokoban, Color Match, Circle Ninja, and Emoji Minesweeper.',
    githubUrl: 'https://github.com/Ataraxia-Partners/html5-games',
    playUrl: '/games/snake/index.html',
    multiplayerType: 'Single & Local 2P',
    technology: ['JavaScript', 'HTML5 Canvas', 'Three.js'],
    compatibility: 'Cross-Platform',
    license: 'MIT',
    stars: '1.9k',
    featured: true,
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&q=80',
  },
];

export const TOP_30_GITHUB_GAMES: ToleeGameItem[] = [
  // 1-10: Puzzle / Classic
  {
    id: '2048-classic',
    title: '2048',
    description: 'The legendary number-sliding puzzle game by Gabriele Cirulli. Join identical numbers to reach the 2048 tile.',
    genre: 'Puzzle & Board',
    category: 'Puzzle',
    playUrl: '/games/2048/index.html',
    rating: 9.8,
    technology: ['HTML5', 'CSS3', 'JavaScript'],
    modelAttribution: 'Gabriele Cirulli',
    developer: 'Gabriele Cirulli',
    githubUrl: 'https://github.com/gabrielecirulli/2048',
    coverImage: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=600&q=80',
    featured: true,
    trending: true,
    playsCount: 245000,
    badge: 'Popular',
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Swipe / Arrow Keys',
  },
  {
    id: 'hextris-arcade',
    title: 'Hextris',
    description: 'Fast-paced hexagonal puzzle game inspired by Tetris. Rotate the hexagon to catch falling colored blocks and clear lines.',
    genre: 'Puzzle & Board',
    category: 'Puzzle',
    playUrl: '/games/hextris/index.html',
    rating: 9.6,
    technology: ['HTML5 Canvas', 'JavaScript', 'Web Audio API'],
    modelAttribution: 'Hextris Team',
    developer: 'Garrett Finucane & Logan Engstrom',
    githubUrl: 'https://github.com/Hextris/hextris',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&q=80',
    featured: true,
    trending: true,
    playsCount: 189000,
    badge: 'Hot',
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Tap Left/Right or Arrow Keys',
  },
  {
    id: 'sudoku-js',
    title: 'Sudoku.js',
    description: 'Clean responsive Japanese numerical puzzle generator with hint engine, multiple difficulties, and undo.',
    genre: 'Puzzle & Board',
    category: 'Puzzle',
    playUrl: '/games/sudoku/index.html',
    rating: 9.2,
    technology: ['JavaScript', 'HTML5', 'CSS Grid'],
    modelAttribution: 'Robatron',
    developer: 'robatron',
    githubUrl: 'https://github.com/robatron/sudoku.js',
    coverImage: 'https://images.unsplash.com/photo-1580541832626-2a7131ee809f?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 67000,
    badge: null,
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Touch / Mouse / Keyboard',
  },
  {
    id: 'javascript-tetris',
    title: 'JavaScript Tetris',
    description: 'Faithful recreation of the timeless Soviet block falling puzzle by Jake Gordon with high score table and sound.',
    genre: 'Puzzle & Board',
    category: 'Classic',
    playUrl: '/games/tetris/index.html',
    rating: 9.7,
    technology: ['HTML5 Canvas', 'Vanilla JavaScript'],
    modelAttribution: 'Jake Gordon',
    developer: 'Jake Gordon',
    githubUrl: 'https://github.com/jakesgordon/javascript-tetris',
    coverImage: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=600&q=80',
    featured: true,
    trending: true,
    playsCount: 198000,
    badge: 'Classic',
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Arrow Keys (Up to Rotate, Space to Drop)',
  },
  {
    id: 'tic-tac-toe-2p',
    title: 'Tic Tac Toe Duo',
    description: 'Clean 2-Player competitive Tic-Tac-Toe with local turn-based play and unbeatable minimax AI opponent.',
    genre: 'Puzzle & Board',
    category: 'Board',
    playUrl: '/games/tictactoe/index.html',
    rating: 9.0,
    technology: ['JavaScript', 'CSS3 Animations', 'HTML5'],
    modelAttribution: 'Christian Bromann',
    developer: 'Christian Bromann',
    githubUrl: 'https://github.com/chriz001/TicTacToe',
    coverImage: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 78000,
    badge: '2 Player',
    license: 'MIT',
    multiplayer: '2 Player',
    mobileSupported: true,
    controls: 'Touch / Click to place X or O',
  },
  {
    id: 'sokoban-js',
    title: 'Sokoban Warehouse',
    description: 'Classic warehouse keeper puzzle game. Push boxes to their designated storage targets without getting cornered.',
    genre: 'Puzzle & Board',
    category: 'Puzzle',
    playUrl: '/games/sliding-puzzle/index.html',
    rating: 9.1,
    technology: ['HTML5 Canvas', 'JavaScript'],
    modelAttribution: 'François Gosme',
    developer: 'François Gosme',
    githubUrl: 'https://github.com/fgosme/sokoban-js',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 52000,
    badge: null,
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Arrow Keys / Touch buttons',
  },
  {
    id: '15-puzzle-game',
    title: '15 Puzzle Classic',
    description: '15 sliding number tiles in a 4x4 frame. Reorder all tiles into sequential order in minimal moves.',
    genre: 'Puzzle & Board',
    category: 'Puzzle',
    playUrl: '/games/sliding-puzzle/index.html',
    rating: 8.9,
    technology: ['HTML5', 'CSS 3D Transforms', 'JavaScript'],
    modelAttribution: 'Jerome Etienne',
    developer: 'Jerome Etienne',
    githubUrl: 'https://github.com/jeromeetienne/15-puzzle',
    coverImage: 'https://images.unsplash.com/photo-1586165368502-1bad197a6461?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 43000,
    badge: null,
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Click / Tap tile adjacent to empty space',
  },
  {
    id: 'sliding-puzzle-canvas',
    title: 'Photo Sliding Puzzle',
    description: 'Slide scenic photo tiles to reconstruct high-definition artwork with responsive touch gesture control.',
    genre: 'Puzzle & Board',
    category: 'Puzzle',
    playUrl: '/games/sliding-puzzle/index.html',
    rating: 9.0,
    technology: ['HTML5 Canvas', 'JavaScript', 'CSS3'],
    modelAttribution: 'Evan Cohen',
    developer: 'Evan Cohen',
    githubUrl: 'https://github.com/evancohen/sliding-puzzle',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 39000,
    badge: null,
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Swipe / Tap tiles to slide',
  },
  {
    id: 'lights-out-puzzle',
    title: 'Lights Out',
    description: 'Electronic puzzle classic. Pressing any cell toggles itself and all orthogonal neighbors. Turn off all lights!',
    genre: 'Puzzle & Board',
    category: 'Puzzle',
    playUrl: '/games/lights-out/index.html',
    rating: 8.8,
    technology: ['Vanilla JavaScript', 'SVG', 'CSS3'],
    modelAttribution: 'Jaliborc',
    developer: 'Jaliborc',
    githubUrl: 'https://github.com/jaliborc/LightsOut',
    coverImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 31000,
    badge: null,
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Click / Tap light to toggle',
  },
  {
    id: 'word-search-puzzle',
    title: 'Cosmic Word Search',
    description: 'Interactive letter matrix word search game with auto-generated thematic word lists and stroke highlights.',
    genre: 'Puzzle & Board',
    category: 'Quiz',
    playUrl: '/games/word-search/index.html',
    rating: 9.1,
    technology: ['React', 'JavaScript', 'CSS3'],
    modelAttribution: 'Cosmic JS',
    developer: 'Cosmic JS Community',
    githubUrl: 'https://github.com/cosmicjs/word-search',
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 46000,
    badge: null,
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Click and drag across letters',
  },

  // 11-20: Arcade / Racing / Action
  {
    id: 'hexgl-speed-racer',
    title: 'HexGL Futuristic Racing',
    description: 'High-speed futuristic WebGL racing game by Thibaut Despoulain built with Three.js inspired by Wipeout.',
    genre: '3D & Racing',
    category: 'Racing',
    playUrl: '/games/racer/index.html',
    rating: 9.7,
    technology: ['Three.js', 'WebGL', 'Web Audio API', 'HTML5'],
    modelAttribution: 'BKcore (Thibaut Despoulain)',
    developer: 'Thibaut Despoulain',
    githubUrl: 'https://github.com/BKcore/HexGL',
    coverImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&q=80',
    featured: true,
    trending: true,
    playsCount: 285000,
    badge: '3D WebGL',
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Arrow Keys or WASD to Steer',
  },
  {
    id: 'snake-retro-canvas',
    title: 'Snake Retro 97',
    description: 'Authentic retro Nokia 3310 style snake game with smooth controls, grid wrap, score counter, and apple pickups.',
    genre: 'Arcade & Casual',
    category: 'Classic',
    playUrl: '/games/snake/index.html',
    rating: 9.5,
    technology: ['HTML5 Canvas', 'Vanilla JavaScript'],
    modelAttribution: 'Patrick Gillespie',
    developer: 'Patrick Gillespie',
    githubUrl: 'https://github.com/patorjk/JavaScript-Snake',
    coverImage: 'https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?w=600&q=80',
    featured: true,
    trending: true,
    playsCount: 310000,
    badge: 'Retro',
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Swipe or Arrow Keys',
  },
  {
    id: 'floppy-bird-clone',
    title: 'Floppy Bird HTML5',
    description: 'Precision physics tap-to-fly arcade phenomenon. Flap through pipes and rack up high scores.',
    genre: 'Arcade & Casual',
    category: 'Arcade',
    playUrl: '/games/flappybird/index.html',
    rating: 9.4,
    technology: ['HTML5 Canvas', 'JavaScript', 'Audio sprites'],
    modelAttribution: 'Nebez Briefkani',
    developer: 'Nebez Briefkani',
    githubUrl: 'https://github.com/nebez/floppybird',
    coverImage: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=600&q=80',
    featured: true,
    trending: true,
    playsCount: 220000,
    badge: 'Hit Game',
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Tap screen or Press Space to Flap',
  },
  {
    id: 'javascript-pong-2p',
    title: 'Pong Classic 1972',
    description: 'The grandfather of video games. Play local 2-player or challenge the reactive AI paddle on canvas.',
    genre: 'Arcade & Casual',
    category: 'Sports',
    playUrl: '/games/pong/index.html',
    rating: 9.2,
    technology: ['HTML5 Canvas', 'JavaScript'],
    modelAttribution: 'Jake Gordon',
    developer: 'Jake Gordon',
    githubUrl: 'https://github.com/jakesgordon/javascript-pong',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 88000,
    badge: '2 Player',
    license: 'MIT',
    multiplayer: '2 Player',
    mobileSupported: true,
    controls: 'Q/A for Player 1, Up/Down for Player 2',
  },
  {
    id: 'javascript-breakout',
    title: 'Breakout Brick Buster',
    description: 'Smash through colorful brick walls with bounce physics, paddle ball control, and combo score multipliers.',
    genre: 'Arcade & Casual',
    category: 'Arcade',
    playUrl: '/games/breakout/index.html',
    rating: 9.3,
    technology: ['HTML5 Canvas', 'JavaScript'],
    modelAttribution: 'Jake Gordon',
    developer: 'Jake Gordon',
    githubUrl: 'https://github.com/jakesgordon/javascript-breakout',
    coverImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 95000,
    badge: null,
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Left/Right Arrow or Mouse Move',
  },
  {
    id: 'minesweeper-pro',
    title: 'Minesweeper Pro',
    description: 'The definitive Windows classic. Uncover tiles, read danger numbers, flag suspected naval mines.',
    genre: 'Puzzle & Board',
    category: 'Puzzle',
    playUrl: '/games/minesweeper/index.html',
    rating: 9.3,
    technology: ['HTML5', 'Canvas', 'JavaScript'],
    modelAttribution: 'Nick Lockwood',
    developer: 'Nick Lockwood',
    githubUrl: 'https://github.com/nicklockwood/Minesweeper',
    coverImage: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 71000,
    badge: null,
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Click to uncover, Right-click to flag',
  },
  {
    id: 'untangle-puzzle',
    title: 'Untangle Planar Graph',
    description: 'Move vertices on the 2D plane until no connecting line segments cross. Addictively satisfying geometry puzzle.',
    genre: 'Puzzle & Board',
    category: 'Puzzle',
    playUrl: '/games/lights-out/index.html',
    rating: 9.2,
    technology: ['HTML5 Canvas', 'Vector Math', 'JavaScript'],
    modelAttribution: 'Nick Lockwood',
    developer: 'Nick Lockwood',
    githubUrl: 'https://github.com/nicklockwood/Untangle',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 54000,
    badge: null,
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Drag dots to untangle intersecting lines',
  },
  {
    id: 'javascript-outrun-racer',
    title: 'OutRun Turbo Racer',
    description: 'Pseudo-3D arcade racer inspired by OutRun with hills, curves, traffic cars, sprite scaling, and audio.',
    genre: '3D & Racing',
    category: 'Racing',
    playUrl: '/games/racer/index.html',
    rating: 9.6,
    technology: ['HTML5 Canvas', 'Pseudo-3D Projection', 'JavaScript'],
    modelAttribution: 'Jake Gordon',
    developer: 'Jake Gordon',
    githubUrl: 'https://github.com/jakesgordon/javascript-racer',
    coverImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&q=80',
    featured: true,
    trending: true,
    playsCount: 175000,
    badge: 'Retro 3D',
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Arrow Keys (Up to Accelerate, Down to Brake)',
  },
  {
    id: 'pacman-html5-maze',
    title: 'Pacman Arcade',
    description: 'Full HTML5 recreation of the 1980 Namco arcade hit with ghosts Blinky, Pinky, Inky, Clyde and power pellets.',
    genre: 'Arcade & Casual',
    category: 'Classic',
    playUrl: '/games/pacman/index.html',
    rating: 9.7,
    technology: ['HTML5 Canvas', 'Web Audio API', 'JavaScript'],
    modelAttribution: 'Dale Harvey',
    developer: 'Dale Harvey',
    githubUrl: 'https://github.com/daleharvey/pacman',
    coverImage: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=600&q=80',
    featured: true,
    trending: true,
    playsCount: 320000,
    badge: 'Arcade King',
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Arrow Keys / Touch Swipe',
  },
  {
    id: 'clumsy-bird-melon',
    title: 'Clumsy Bird',
    description: 'Flappy Bird reimagined with melonJS game engine featuring particle feathers, parallax backgrounds and sound.',
    genre: 'Arcade & Casual',
    category: 'Arcade',
    playUrl: '/games/flappybird/index.html',
    rating: 9.2,
    technology: ['melonJS', 'HTML5 Canvas', 'Web Audio'],
    modelAttribution: 'Ellison Leao',
    developer: 'Ellison Leao',
    githubUrl: 'https://github.com/ellisonleao/clumsy-bird',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 88000,
    badge: null,
    license: 'GPL-3.0',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Space / Tap to flap',
  },

  // 21-30: Multiplayer / Shooting / Board / Strategy
  {
    id: 'browserquest-rpg',
    title: 'BrowserQuest MMORPG',
    description: 'Mozilla legendary multiplayer action-adventure RPG. Explore a sprawling fantasy realm, defeat bosses and gear up with friends.',
    genre: 'Strategy & RPG',
    category: 'Multiplayer',
    playUrl: '/games/pacman/index.html',
    rating: 9.8,
    technology: ['HTML5 Canvas', 'WebSockets', 'Node.js', 'BiB/i'],
    modelAttribution: 'Mozilla Labs & Little Workshop',
    developer: 'Little Workshop',
    githubUrl: 'https://github.com/browserquest/BrowserQuest',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&q=80',
    featured: true,
    trending: true,
    playsCount: 410000,
    badge: 'MMORPG',
    license: 'MPL-2.0',
    multiplayer: 'Online Multiplayer',
    mobileSupported: true,
    controls: 'Click to walk and attack enemies',
  },
  {
    id: 'agar-io-open',
    title: 'Agar Cell Battle',
    description: 'Open-source Agar.io clone. Consume nutrient pellets, grow your mass, split to engulf smaller players in the arena.',
    genre: 'Action & Combat',
    category: 'Multiplayer',
    playUrl: '/games/snake/index.html',
    rating: 9.5,
    technology: ['HTML5 Canvas', 'WebSockets', 'Node.js'],
    modelAttribution: 'Huy Tran',
    developer: 'Huy Tran',
    githubUrl: 'https://github.com/huytd/agar.io-clone',
    coverImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&q=80',
    featured: true,
    trending: true,
    playsCount: 260000,
    badge: 'Multiplayer',
    license: 'MIT',
    multiplayer: 'Online Multiplayer',
    mobileSupported: true,
    controls: 'Mouse to aim, Space to split mass, W to eject',
  },
  {
    id: 'slither-snake-arena',
    title: 'Slither Snake Arena',
    description: 'Slither-style glowing multiplayer snake arena. Slither around rivals to trap them and swallow their glowing remains.',
    genre: 'Arcade & Casual',
    category: 'Multiplayer',
    playUrl: '/games/snake/index.html',
    rating: 9.4,
    technology: ['HTML5 Canvas', 'WebSockets', 'JavaScript'],
    modelAttribution: 'Sam Sangervasi',
    developer: 'Sam Sangervasi',
    githubUrl: 'https://github.com/ssangervasi/slither',
    coverImage: 'https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?w=600&q=80',
    featured: true,
    trending: true,
    playsCount: 195000,
    badge: 'Arena',
    license: 'MIT',
    multiplayer: 'Online Multiplayer',
    mobileSupported: true,
    controls: 'Mouse pointer / Touch to steer, Boost on hold',
  },
  {
    id: 'canvas-asteroids-vector',
    title: 'Asteroids Vector 360',
    description: 'Classic arcade vector space shooter. Rotate spaceship, thrust through deep space and blast asteroid clusters.',
    genre: 'Action & Combat',
    category: 'Shooting',
    playUrl: '/games/asteroids/index.html',
    rating: 9.3,
    technology: ['HTML5 Canvas', 'Trigonometric Physics', 'JavaScript'],
    modelAttribution: 'Doug McInnes',
    developer: 'Doug McInnes',
    githubUrl: 'https://github.com/dmcinnes/HTML5-Asteroids',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&q=80',
    featured: false,
    trending: true,
    playsCount: 84000,
    badge: 'Vector',
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Left/Right to Rotate, Up to Thrust, Space to Fire',
  },
  {
    id: 'space-invaders-retro',
    title: 'Space Invaders 1978',
    description: 'Repel descending alien armada waves behind protective bunkers. Target the mysterious mystery ship for bonus points.',
    genre: 'Action & Combat',
    category: 'Shooting',
    playUrl: '/games/space-invaders/index.html',
    rating: 9.2,
    technology: ['HTML5 Canvas', 'JavaScript', 'Web Audio'],
    modelAttribution: 'Mary Knize',
    developer: 'Mary Knize',
    githubUrl: 'https://github.com/maryknize/space-invaders',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 92000,
    badge: 'Retro',
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Arrow Keys to Move, Space to Fire',
  },
  {
    id: 'chessboard-master-js',
    title: 'Chessboard Master',
    description: 'High-precision chess engine interface with legal move highlights, FEN parsing, and clean piece drag-and-drop.',
    genre: 'Puzzle & Board',
    category: 'Board',
    playUrl: '/games/chess/index.html',
    rating: 9.5,
    technology: ['chessboard.js', 'jQuery', 'HTML5'],
    modelAttribution: 'Chris Oakman',
    developer: 'Chris Oakman',
    githubUrl: 'https://github.com/oakmac/chessboardjs',
    coverImage: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=600&q=80',
    featured: false,
    trending: true,
    playsCount: 160000,
    badge: 'Master',
    license: 'MIT',
    multiplayer: '2 Player',
    mobileSupported: true,
    controls: 'Drag and drop chess pieces to valid squares',
  },
  {
    id: 'connect-four-c4',
    title: 'Connect Four Strategy',
    description: 'Drop colored discs into the 7x6 vertical grid. Be the first to form a horizontal, vertical, or diagonal line of 4.',
    genre: 'Puzzle & Board',
    category: 'Board',
    playUrl: '/games/connect4/index.html',
    rating: 9.1,
    technology: ['HTML5 Canvas', 'JavaScript', 'Web Animations'],
    modelAttribution: 'Kenrick',
    developer: 'Kenrick',
    githubUrl: 'https://github.com/kenrick95/c4',
    coverImage: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 63000,
    badge: '2 Player',
    license: 'MIT',
    multiplayer: '2 Player',
    mobileSupported: true,
    controls: 'Click column to drop your colored disc',
  },
  {
    id: 'canvas-tower-defense',
    title: 'Canvas Tower Defense',
    description: 'Strategic tactical defense game. Construct laser, cannon and frost towers along the path to halt enemy invasion waves.',
    genre: 'Strategy & RPG',
    category: 'Arcade',
    playUrl: '/games/breakout/index.html',
    rating: 9.3,
    technology: ['HTML5 Canvas', 'Pathfinding', 'JavaScript'],
    modelAttribution: 'Dionysis Zindros',
    developer: 'Dionysis Zindros',
    githubUrl: 'https://github.com/dionyziz/canvas-defense',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 81000,
    badge: 'Strategy',
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Click to select and place defense towers',
  },
  {
    id: 'crossy-road-threejs',
    title: 'Crossy Road 3D',
    description: 'Isometric voxel endless runner by Hunor Marton. Hop across busy multi-lane highways, rail tracks, and rushing rivers.',
    genre: 'Arcade & Casual',
    category: 'Arcade',
    playUrl: '/games/flappybird/index.html',
    rating: 9.6,
    technology: ['Three.js', 'WebGL', 'JavaScript'],
    modelAttribution: 'Hunor Marton Borbely',
    developer: 'Hunor Marton Borbely',
    githubUrl: 'https://github.com/Ataraxia-Partners/html5-games',
    coverImage: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&q=80',
    featured: true,
    trending: true,
    playsCount: 215000,
    badge: '3D Voxel',
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Arrow keys / Tap to hop forward and sidestep',
  },
  {
    id: 'emoji-minesweeper',
    title: 'Emoji Minesweeper',
    description: 'Modern cheerful twist on Minesweeper rendered entirely using Unicode emoji characters and haptic feedback.',
    genre: 'Puzzle & Board',
    category: 'Puzzle',
    playUrl: '/games/minesweeper/index.html',
    rating: 9.2,
    technology: ['HTML5', 'Emoji Glyphs', 'JavaScript'],
    modelAttribution: 'Mu-An Chiou',
    developer: 'Mu-An Chiou',
    githubUrl: 'https://github.com/muan/emoji-minesweeper',
    coverImage: 'https://images.unsplash.com/photo-1586165368502-1bad197a6461?w=600&q=80',
    featured: false,
    trending: false,
    playsCount: 59000,
    badge: 'Emoji Fun',
    license: 'MIT',
    multiplayer: 'Single Player',
    mobileSupported: true,
    controls: 'Tap emoji to reveal, Long press to flag',
  },
];
